pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                withMaven(maven : 'apache-maven-3.8.1') {
                    bat 'mvn -f java-tomcat-sample/pom.xml clean package'
                }
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}